HOCS-2493 : detect pushes to hotfix branches
UKHomeOffice/hocs-notify pull request #12
Opened 2021-02-26 15:29 UTC by MarkWrightBjss

2021-03-01 16:43 UTC, zuzak submitted a review, later dismissed
This won't work at the moment, as the `docker-build` step only tuns on a push to master or a tag. This means the pipeline'll skip straight to installing a non-existent Docker image.

2021-03-02 11:37 UTC, Paulcr-ho requested changes

2021-03-04 11:11 UTC, Paulcr-ho approved these changes

2021-03-10 09:34 UTC, Paulcr-ho commented
> This won't work at the moment, as the `docker-build` step only tuns on a push to master or a tag. This means the pipeline'll skip straight to installing a non-existent Docker image.

This has been rectified and can be marked as resolved.

2021-03-16 10:02 UTC, merged